apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-model-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iris-model-api
  template:
    metadata:
      labels:
        app: iris-model-api
    spec:
      containers:
      - name: iris-model-api
        image: iris-serve:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: iris-model-service
spec:
  selector:
    app: iris-model-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
